### ISSUE TITLE
Application state necessary?

### ISSUE THREAD

**Issue by dmjio** [ptigwe/hs2048#3]
I like how the Haskell ADT is depicted on the left-hand side of the page, but do you think it's necessary to include during gameplay? Honestly, I wouldn't mind removing it altogether.

**Comment by ptigwe** [comment]
You are right, it doesn't need to be there. I initially put it there as it made debugging (especially in the earlier stages) a lot easier. I've currently partially removed it. It is still accessible in the code, but by default should not be visible. Guess I might have to do the same with hs-flatris.
