### ISSUE TITLE
nix-build failing with recent nixpkgs

### ISSUE THREAD

**Issue by mpickering** [ptigwe/hs2048#8]
Please can you specify a nixpkgs commit which is able to build the project? 

It is failing with 360e01955003333f7d545eedf8b773311a2b7646

**Comment by ptigwe** [comment]
@mpickering I've updated the `default.nix` file to reflect the nixpkgs commit as well as an update to the most recent version of miso. Let me know if it doesn't work.

Also, `stack` should also be able to build the project.
